        Dim UpdateFaces As Action(Of SolidEdgeFramework.FaceStyle) =
            Sub(_CurrentMaterialFaceStyle)
                Dim Model As SolidEdgePart.Model
                Dim Body As SolidEdgeGeometry.Body
                Dim Faces As SolidEdgeGeometry.Faces
                Dim Faces2 As New List(Of SolidEdgeGeometry.Face)
                Dim Face As SolidEdgeGeometry.Face

                Dim FaceOverrides As New Dictionary(Of Integer, SolidEdgeFramework.FaceStyle)
                Dim BodyOverride As SolidEdgeFramework.FaceStyle = Nothing

                If (Models.Count > 0) And (Models.Count < 300) Then
                    For Each Model In Models
                        ' Some Models do not have a Body
                        Try
                            Body = CType(Model.Body, SolidEdgeGeometry.Body)
                            'Body.Style = _CurrentMaterialFaceStyle
                            If Body.Style IsNot Nothing Then
                                BodyOverride = Body.Style
                            End If

                            'Body.Faces
                            Faces = CType(Body.Faces(SolidEdgeGeometry.FeatureTopologyQueryTypeConstants.igQueryAll), SolidEdgeGeometry.Faces)

                            For Each Face In Faces
                                If Face.Style IsNot Nothing Then
                                    FaceOverrides(Face.ID) = Face.Style
                                End If
                            Next

                            Body.ClearOverrides()
                            'MsgBox("Body.ClearOverrides()")

                            SEApp.DoIdle()

                            If BodyOverride IsNot Nothing Then
                                Body.Style = BodyOverride
                                BodyOverride = Nothing
                            End If

                            If FaceOverrides.Count > 0 Then
                                For Each Face In Faces
                                    If FaceOverrides.Keys.Contains(Face.ID) Then
                                        Face.Style = FaceOverrides(Face.ID)
                                    End If

                                Next
                                FaceOverrides.Clear()

                            End If

                            MsgBox("Done with faces")

                        Catch ex As Exception
                            MsgBox("Exception" + Chr(13) + ex.ToString)
                        End Try
                    Next

                ElseIf Models.Count >= 300 Then
                    ExitStatus = 1
                    ErrorMessageList.Add(String.Format("{0} models exceeds maximum to process", Models.Count.ToString))
                End If

            End Sub
